name: bazaarIQ
description: A mobile-first ad intelligence tool for serious ecommerce sellers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
